# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d274fdd31b9b158691b878738fddd2df18c35eb2be30ac1c8d08c0080bcd023e94d22580bf65ed89e4f29ab777d9c93bf497864d5129e60b47099f2797079601

test:
  secret_key_base: 74f7e70e4e2f199d1481b0f63288b71a7f6972e8ef4fb014d204ec9cc0d5b0cf57dbffacca74e7014613b9e558fce86ffede1dbb90567bbe0fc56cf4eb91028b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
